---
title: "07 CSI online: Post-hoc power"
author: "Kirsten Stark"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages

```{r load packages}
library(dplyr)
library(tidyr)
library(lme4)
library(lmerTest)
library(Rmisc)
library(Cairo)
#library(strengejacke)
library(ggplot2)
library(sjPlot)

options(scipen=999)

rm(list = ls())
options( "encoding" = "UTF-8" )
```

```{r}
powersim <- read.csv(here::here("results", "power_sim", "posthoc_powersim.csv"))
#mixedpower <- read.csv(here::here("data", "posthoc_mixedpower.csv"))
```

Verbal - different subject sizes

Make plots suitable for APA format, font sizes can be adjusted

```{r apatheme}
apatheme <- theme_bw()+
  theme(plot.title=element_text(family="Arial",size=20,hjust = .5),
        panel.grid.major=element_blank(), panel.grid.minor=element_blank(),
        panel.border=element_blank(),axis.line=element_line(),
        text=element_text(family="Arial",size=14))
condition.colors <- RColorBrewer::brewer.pal(9, name = "YlGnBu")[c(6, 9)]
names(condition.colors) <- c("Spoken naming", "Typed naming")
```



```{r}
df <- powersim %>% filter(name == "verbal_s8_t_around109" |
                            name == "verbal_s24_t_around109" |
                            name == "verbal_s16_t_around109" |
                            name == "verbal_s30_t_around109" |
                            name == "typing_s30_t_around109" |
                            name == "typing_s24_t_around109" |
                            name == "typing_s16_t_around109" |
                            name == "typing_s8_t_around109") %>% 
  mutate(Experiment = case_when(startsWith(name,"verbal") ~ "Spoken naming",
                                startsWith(name,"typing") ~ "Typed naming")) %>%
  mutate(Experiment = as.factor(Experiment)) %>%
  mutate(nsubjects_p = case_when(Experiment =="Spoken naming" ~ nsubjects-0.6, 
                                 Experiment =="Typed naming" ~ nsubjects+0.6)) %>%
  droplevels()

(plot_subj <- df %>% 
    ggplot(., aes(x=nsubjects, group = Experiment)) +
    geom_point(aes(y = mean, color = Experiment), size = 2)+
    geom_line(aes(y = mean, color = Experiment),size = 0.5, linetype = "dashed")+
    #stat_summary(fun=mean,  geom="line", size = 0.5, group = 1, linetype = "dashed") +
    geom_errorbar(aes(ymin=lower, ymax=upper, color=Experiment ), width =.1) +
    geom_jitter(aes(x=nsubjects_p, y=pval, group=Experiment, color=Experiment), 
                size = 0.5, width = 0.5,  alpha = 0.2)+
    geom_hline(yintercept=0.05, linetype = "longdash")+
    geom_hline(yintercept=0.80, linetype = "dotted")+
    apatheme+
    scale_x_continuous(breaks = c(8, 16, 24, 30))+
    scale_y_continuous(name = "Power (1000 simulations)", 
                       sec.axis = sec_axis(~., name = "p-values"))+
    #scale_y_continuous(limits = c(0.990, 1)) +
                       #breaks = c(1100, 1150, 1200, 1250, 1300, 1350)) + 
    scale_color_manual(values = condition.colors) +
    #scale_y_continuous(name="Power (1000 simulations)")+
    labs(x="N (Subjects)\n24 Categories")+#,y ="Power (1000 simulations)") + #+
  # annotate(geom="text", x=1.5, y=1330, label="n = 30", 
  #         color="black", size = 8))
    #ggtitle("Power - different sample sizes")+
    theme(legend.position = c(0.7, 0.6), legend.title= element_blank()) +
    theme(
    axis.title.y = element_text(margin = margin(0,10,0,0)),
    axis.title.x = element_text(margin = margin(10,0,0,0))))

```


```{r}
df <- powersim %>% filter(name == "verbal_s30_t_around109" |
                            name == "verbal_s30_cat16" |
                            name == "verbal_s30_cat8" |
                            name == "verbal_s30_cat4" |
                            name == "typing_s30_t_around109" |
                            name == "typing_s30_cat16" |
                            name == "typing_s30_cat8" |
                            name == "typing_s30_cat4") %>% 
  mutate(Experiment = case_when(startsWith(name,"verbal") ~ "Spoken naming",
                                startsWith(name,"typing") ~ "Typed naming")) %>%
  mutate(Experiment = as.factor(Experiment)) %>%
  mutate(ncat = case_when(name == "verbal_s30_t_around109" ~24,
                            name == "verbal_s30_cat16" ~16,
                            name == "verbal_s30_cat8" ~8,
                            name == "verbal_s30_cat4" ~4,
                            name == "typing_s30_t_around109" ~24,
                            name == "typing_s30_cat16" ~16,
                            name == "typing_s30_cat8" ~8,
                            name == "typing_s30_cat4" ~4)) %>%
  mutate(ncat_p = case_when(Experiment =="Spoken naming" ~ ncat-0.6, 
                                 Experiment =="Typed naming" ~ ncat+0.6)) %>%
  droplevels()

(plot_cat <- df %>% 
    ggplot(., aes(x=ncat, group = Experiment)) +
    geom_point(aes(y = mean, colour = Experiment), size = 2)+
    geom_line(aes(y = mean, colour = Experiment),size = 0.5, linetype = "dashed")+
    #stat_summary(fun=mean,  geom="line", size = 0.5, group = 1, linetype = "dashed") +
    geom_errorbar(aes(ymin=lower, ymax=upper, group=Experiment, color = Experiment), 
                  width =.1) +
    geom_jitter(aes(x=ncat_p, y=pval, group=Experiment, color=Experiment), 
                size = 0.5, width = 0.5,  alpha = 0.2)+
    geom_hline(yintercept=0.05, linetype = "longdash")+
    geom_hline(yintercept=0.80, linetype = "dotted")+
    apatheme+
    scale_x_continuous(breaks = c(4,8, 16, 24))+
    scale_color_manual(values = condition.colors) +
    scale_y_continuous(name = "Power (1000 simulations)", 
                       sec.axis = sec_axis(~., name = "p-values"))+
    #scale_y_continuous(limits = c(0.990, 1)) +
                       #breaks = c(1100, 1150, 1200, 1250, 1300, 1350)) + 
    labs(x="N (Categories)\n30 Subjects")+#,y ="Power (1000 simulations)")+
  # annotate(geom="text", x=1.5, y=1330, label="n = 30", 
  #         color="black", size = 8))
    #ggtitle("Power - different numbers of categories")+
    theme(legend.position = c(0.7, 0.6), legend.title= element_blank()) +
    theme(
    axis.title.y = element_text(margin = margin(0,10,0,0)),
    axis.title.x = element_text(margin = margin(10,0,0,0))))

```

```{r}
(cowplot::plot_grid(plot_subj, plot_cat,
          nrow = 1, labels = c("A", "B"), label_fontfamily = "Helvetica") %>% 
  ggsave(filename = here::here("figures",
                               "CSI_online_posthoc_power"),
         width = 20, height = 13, units = "cm", dpi = 300, 
         device = cairo_pdf))
#embedFonts(file = here::here("figures", "CSI_online_posthoc_power"))
```



```{r}
# mixedpower<- mixedpower %>%
#   filter(Var2 != "mode" | Var2 != "effect") %>%
#   mutate(Var2 = as.numeric(Var2)) %>%
#   droplevels()
# mixedpower$min <- NA
# mixedpower$firstqu <- NA
# mixedpower$median <- NA
# mixedpower$mean <- NA
# mixedpower$thirdqu <- NA
# mixedpower$max <- NA
# for(i in 1:nrow(mixedpower)) {
#   v <- strsplit(mixedpower$Freq[i],split=':', fixed=TRUE)
#   v <- v[[1]]
#  # print(v)
#   if(!is.na(v)){
#   if(v[1] =="Min.   "){
#     mixedpower$min[i] <- v[2]
#   }
#   if(v[1] =="1st Qu."){
#     mixedpower$firstqu[i-1] <- v[2]
#   }
#   if(v[1] =="Median "){
#     mixedpower$median[i-2] <- v[2]
#     }  
#   if(v[1] =="Mean   "){
#     mixedpower$mean[i-3] <- v[2]
#     }  
#   if(v[1] =="3rd Qu."){
#     mixedpower$thirdqu[i-4] <- v[2]
#     }
#   if(v[1] =="Max.   "){
#     mixedpower$max[i-5] <- v[2]
#   }
# }
# }
# mixedpower$min <- as.numeric(as.character(mixedpower$min))
# mixedpower$mean <- as.numeric(as.character(mixedpower$mean))
# mixedpower$max <- as.numeric(as.character(mixedpower$max))
```

```{r}
# df <- mixedpower %>% filter(Var1 == "verbal_subject" ) %>% 
#   filter(Var2 != "mode" | Var2 != "effect") %>%
#   filter(!is.na(min)) %>%
#   mutate(Var2 = as.numeric(Var2)) %>%
#   droplevels()
# 
# (plot <- df %>% 
#     ggplot(., aes(x=Var2)) +
#     geom_point(aes(y = mean), size = 2)+
#     geom_line(aes(y = mean),size = 0.5, group = 1, linetype = "dashed")+
#     #stat_summary(fun=mean,  geom="line", size = 0.5, group = 1, linetype = "dashed") +
#     #geom_errorbar(aes(ymin=min, ymax=max), width =.1) +
#     #geom_jitter(aes(y = pval/coeff), width = 0.5)+
#     apatheme+
#     scale_x_continuous(breaks = c(10,12,14,16,18,20,22,24,26,28,30))+
#     #scale_y_continuous(name = "Power", limits = c(0.990, 1.0), 
#     #                   sec.axis = sec_axis(~.*coeff, name = "p-values"))+
#     #scale_y_continuous(limits = c(0.990, 1)) +
#                        #breaks = c(1100, 1150, 1200, 1250, 1300, 1350)) + 
#     labs(x="N (Subjects)",y ="Power (1000 simulations)") + #+
#   # annotate(geom="text", x=1.5, y=1330, label="n = 30", 
#   #         color="black", size = 8))
#     ggtitle("Verbal naming - different sample sizes \n Mixedpower package")+
#     theme(
#     axis.title.y = element_text(margin = margin(0,10,0,0)),
#     axis.title.x = element_text(margin = margin(10,0,0,0))))

```

```{r}
# df <- mixedpower %>% filter(Var1 == "verbal_category" ) %>% 
#   filter(Var2 != "mode" | Var2 != "effect") %>%
#   filter(!is.na(min)) %>%
#   mutate(Var2 = as.numeric(Var2)) %>%
#   droplevels()
# 
# (plot <- df %>% 
#     ggplot(., aes(x=Var2)) +
#     geom_point(aes(y = mean), size = 2)+
#     geom_line(aes(y = mean),size = 0.5, group = 1, linetype = "dashed")+
#     #stat_summary(fun=mean,  geom="line", size = 0.5, group = 1, linetype = "dashed") +
#     #geom_errorbar(aes(ymin=min, ymax=max), width =.1) +
#     #geom_jitter(aes(y = pval/coeff), width = 0.5)+
#     apatheme+
#     scale_x_continuous(breaks = c(8,12,16,20,24))+
#     #scale_y_continuous(name = "Power", limits = c(0.990, 1.0), 
#     #                   sec.axis = sec_axis(~.*coeff, name = "p-values"))+
#     #scale_y_continuous(limits = c(0.990, 1)) +
#                        #breaks = c(1100, 1150, 1200, 1250, 1300, 1350)) + 
#     labs(x="N (Category)",y ="Power (1000 simulations)") + #+
#   # annotate(geom="text", x=1.5, y=1330, label="n = 30", 
#   #         color="black", size = 8))
#     ggtitle("Verbal naming - different numbers of categories \n Mixedpower package")+
#     theme(
#     axis.title.y = element_text(margin = margin(0,10,0,0)),
#     axis.title.x = element_text(margin = margin(10,0,0,0))))

```

```{r}
# ggplot(data, aes(x=day)) +
#   
#   geom_line( aes(y=temperature)) + 
#   geom_line( aes(y=price / coeff)) + # Divide by 10 to get the same range than the temperature
#   
#   scale_y_continuous(
#     
#     # Features of the first axis
#     name = "First Axis",
#     
#     # Add a second axis and specify its features
#     sec.axis = sec_axis(~.*coeff, name="Second Axis")
#   )
# 
# coeff <- 0.000000075
# (plot <- df %>% 
#     ggplot(., aes(x=nsubjects)) +
#     geom_point(aes(y = mean), size = 2)+
#     geom_line(aes(y = mean),size = 0.5, group = 1, linetype = "dashed")+
#     #stat_summary(fun=mean,  geom="line", size = 0.5, group = 1, linetype = "dashed") +
#     geom_errorbar(aes(ymin=lower, ymax=upper), width =.1) +
#     geom_jitter(aes(y = pval/coeff), width = 0.5)+
#     apatheme+
#     scale_x_continuous(breaks = c(22, 24, 26, 30))+
#     scale_y_continuous(name = "Power", limits = c(0.990, 1.0), 
#                        sec.axis = sec_axis(~.*coeff, name = "p-values"))+
#     #scale_y_continuous(limits = c(1120, 1340), breaks =seq(1120,1340, by = 20)) +
#                        #breaks = c(1100, 1150, 1200, 1250, 1300, 1350)) + 
#     #labs(x="Ordinal Position ",y ="RT (ms)") + #+
#   # annotate(geom="text", x=1.5, y=1330, label="n = 30", 
#   #         color="black", size = 8))
#     theme(
#     axis.title.y = element_text(margin = margin(0,10,0,0)),
#     axis.title.x = element_text(margin = margin(10,0,0,0))))

```
